# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import FluxConfiguration
    from ._models_py3 import FluxConfigurationsList
    from ._models_py3 import GitRepositoryDefinition
    from ._models_py3 import KustomizationDefinition
    from ._models_py3 import OperationStatusList
    from ._models_py3 import OperationStatusResult
    from ._models_py3 import ProxyResource
    from ._models_py3 import RepositoryRefDefinition
    from ._models_py3 import Resource
    from ._models_py3 import ResourceProviderOperation
    from ._models_py3 import ResourceProviderOperationDisplay
    from ._models_py3 import ResourceProviderOperationList
    from ._models_py3 import SystemData
except (SyntaxError, ImportError):
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import FluxConfiguration  # type: ignore
    from ._models import FluxConfigurationsList  # type: ignore
    from ._models import GitRepositoryDefinition  # type: ignore
    from ._models import KustomizationDefinition  # type: ignore
    from ._models import OperationStatusList  # type: ignore
    from ._models import OperationStatusResult  # type: ignore
    from ._models import ProxyResource  # type: ignore
    from ._models import RepositoryRefDefinition  # type: ignore
    from ._models import Resource  # type: ignore
    from ._models import ResourceProviderOperation  # type: ignore
    from ._models import ResourceProviderOperationDisplay  # type: ignore
    from ._models import ResourceProviderOperationList  # type: ignore
    from ._models import SystemData  # type: ignore

from ._source_control_configuration_client_enums import (
    CreatedByType,
    Enum0,
    Enum1,
    KustomizationValidationType,
    ProvisioningState,
    ScopeType,
    SourceKindType,
    SyncStateType,
)

__all__ = [
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'FluxConfiguration',
    'FluxConfigurationsList',
    'GitRepositoryDefinition',
    'KustomizationDefinition',
    'OperationStatusList',
    'OperationStatusResult',
    'ProxyResource',
    'RepositoryRefDefinition',
    'Resource',
    'ResourceProviderOperation',
    'ResourceProviderOperationDisplay',
    'ResourceProviderOperationList',
    'SystemData',
    'CreatedByType',
    'Enum0',
    'Enum1',
    'KustomizationValidationType',
    'ProvisioningState',
    'ScopeType',
    'SourceKindType',
    'SyncStateType',
]
